language: node_js
node_js:
  - "7"
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 192.241.143.96
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
script: 
  - gulp build
after_success:
  - "./scripts/deploy.sh"